Update pages-nuxtjs-example.yml

diff --git a/.github/workflows/pages-nuxtjs-example.yml b/.github/workflows/pages-nuxtjs-example.yml
--- a/.github/workflows/pages-nuxtjs-example.yml
+++ b/.github/workflows/pages-nuxtjs-example.yml
@@ -24,6 +24,9 @@ concurrency:
   group: "pages"
   cancel-in-progress: false
 
+env:
+  WORKING_DIR: app
+
 defaults:
   run:
     working-directory: app
@@ -38,18 +41,20 @@ jobs:
       - name: Detect package manager
         id: detect-package-manager
         run: |
-          if [ -f "${{ github.workspace }}/yarn.lock" ]; then
-            echo "manager=yarn" >> $GITHUB_OUTPUT
-            echo "command=install" >> $GITHUB_OUTPUT
-            exit 0
-          elif [ -f "${{ github.workspace }}/package.json" ]; then
-            echo "manager=npm" >> $GITHUB_OUTPUT
-            echo "command=ci" >> $GITHUB_OUTPUT
-            exit 0
-          else
-            echo "Unable to determine package manager"
-            exit 1
-          fi
+          # if [ -f "${{ github.workspace }}/yarn.lock" ]; then
+          #   echo "manager=yarn" >> $GITHUB_OUTPUT
+          #   echo "command=install" >> $GITHUB_OUTPUT
+          #   exit 0
+          # elif [ -f "${{ github.workspace }}/package.json" ]; then
+          #   echo "manager=npm" >> $GITHUB_OUTPUT
+          #   echo "command=ci" >> $GITHUB_OUTPUT
+          #   exit 0
+          # else
+          #   echo "Unable to determine package manager"
+          #   exit 1
+          # fi
+          echo "manager=npm" >> $GITHUB_OUTPUT
+          echo "command=ci" >> $GITHUB_OUTPUT
       - name: Setup Node
         uses: actions/setup-node@v4
         with:
@@ -63,6 +68,7 @@ jobs:
           #
           # You may remove this line if you want to manage the configuration yourself.
           static_site_generator: nuxt
+          base_path: env.WORKING_DIR
       - name: Restore cache
         uses: actions/cache@v4
         with:
@@ -79,7 +85,7 @@ jobs:
       - name: Upload artifact
         uses: actions/upload-pages-artifact@v3
         with:
-          path: ./dist
+          path: ./app/dist
 
   # Deployment job
   deploy:
