Update pages-nuxtjs-example.yml

diff --git a/.github/workflows/pages-nuxtjs-example.yml b/.github/workflows/pages-nuxtjs-example.yml
--- a/.github/workflows/pages-nuxtjs-example.yml
+++ b/.github/workflows/pages-nuxtjs-example.yml
@@ -25,11 +25,11 @@ concurrency:
   cancel-in-progress: false
 
 env:
-  WORKING_DIR: app
+  WORKING_DIR: ./app
 
 defaults:
   run:
-    working-directory: app
+    working-directory: ./app
 
 jobs:
   # Build job
@@ -41,26 +41,24 @@ jobs:
       - name: Detect package manager
         id: detect-package-manager
         run: |
-          # if [ -f "${{ github.workspace }}/yarn.lock" ]; then
-          #   echo "manager=yarn" >> $GITHUB_OUTPUT
-          #   echo "command=install" >> $GITHUB_OUTPUT
-          #   exit 0
-          # elif [ -f "${{ github.workspace }}/package.json" ]; then
-          #   echo "manager=npm" >> $GITHUB_OUTPUT
-          #   echo "command=ci" >> $GITHUB_OUTPUT
-          #   exit 0
-          # else
-          #   echo "Unable to determine package manager"
-          #   exit 1
-          # fi
-          echo "manager=npm" >> $GITHUB_OUTPUT
-          echo "command=ci" >> $GITHUB_OUTPUT
+          if [ -f "${{ github.workspace }}/${{ env.WORKING_DIR }}/yarn.lock" ]; then
+            echo "manager=yarn" >> $GITHUB_OUTPUT
+            echo "command=install" >> $GITHUB_OUTPUT
+            exit 0
+          elif [ -f "${{ github.workspace }}/${{ env.WORKING_DIR }}/package.json" ]; then
+            echo "manager=npm" >> $GITHUB_OUTPUT
+            echo "command=ci" >> $GITHUB_OUTPUT
+            exit 0
+          else
+            echo "Unable to determine package manager"
+            exit 1
+          fi
       - name: Setup Node
         uses: actions/setup-node@v4
         with:
           node-version: "20"
           cache: ${{ steps.detect-package-manager.outputs.manager }}
-          cache-dependency-path: env.WORKING_DIR
+          cache-dependency-path: ${{ env.WORKING_DIR }}
       - name: Setup Pages
         uses: actions/configure-pages@v5
         with:
@@ -69,7 +67,7 @@ jobs:
           #
           # You may remove this line if you want to manage the configuration yourself.
           static_site_generator: nuxt
-          base_path: env.WORKING_DIR
+          base_path: ${{ env.WORKING_DIR }}
       - name: Restore cache
         uses: actions/cache@v4
         with:
@@ -86,7 +84,7 @@ jobs:
       - name: Upload artifact
         uses: actions/upload-pages-artifact@v3
         with:
-          path: ./app/dist
+          path: ${{ env.WORKING_DIR }}/dist
 
   # Deployment job
   deploy:
